apiVersion: azuredevops.upbound.io/v1alpha1
kind: Environment
metadata:
  annotations:
    crossplane.io/external-name: "17"
  name: example-01
spec:
  deletionPolicy: Orphan
  managementPolicy: FullControl
  forProvider:
    name: example-01
    description: Example Environment desc - demo
    projectIdRef:
      name: example-01
