/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupObservation struct {

	// Boolean that indicate if this variable group is shared by all pipelines of this project.
	AllowAccess *bool `json:"allowAccess,omitempty" tf:"allow_access,omitempty"`

	// The description of the Variable Group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the Variable Group returned after creation in Azure DevOps.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A list of key_vault blocks as documented below.
	KeyVault []KeyVaultObservation `json:"keyVault,omitempty" tf:"key_vault,omitempty"`

	// The name of the Variable Group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// One or more variable blocks as documented below.
	Variable []VariableObservation `json:"variable,omitempty" tf:"variable,omitempty"`
}

type GroupParameters struct {

	// Boolean that indicate if this variable group is shared by all pipelines of this project.
	// +kubebuilder:validation:Optional
	AllowAccess *bool `json:"allowAccess,omitempty" tf:"allow_access,omitempty"`

	// The description of the Variable Group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A list of key_vault blocks as documented below.
	// +kubebuilder:validation:Optional
	KeyVault []KeyVaultParameters `json:"keyVault,omitempty" tf:"key_vault,omitempty"`

	// The name of the Variable Group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// One or more variable blocks as documented below.
	// +kubebuilder:validation:Optional
	Variable []VariableParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type KeyVaultObservation struct {

	// The name of the Azure key vault to link secrets from as variables.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set the Azure Key Vault Secret search depth. Defaults to 20.
	SearchDepth *float64 `json:"searchDepth,omitempty" tf:"search_depth,omitempty"`

	// The id of the Azure subscription endpoint to access the key vault.
	ServiceEndpointID *string `json:"serviceEndpointId,omitempty" tf:"service_endpoint_id,omitempty"`
}

type KeyVaultParameters struct {

	// The name of the Azure key vault to link secrets from as variables.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Set the Azure Key Vault Secret search depth. Defaults to 20.
	// +kubebuilder:validation:Optional
	SearchDepth *float64 `json:"searchDepth,omitempty" tf:"search_depth,omitempty"`

	// The id of the Azure subscription endpoint to access the key vault.
	// +kubebuilder:validation:Required
	ServiceEndpointID *string `json:"serviceEndpointId" tf:"service_endpoint_id,omitempty"`
}

type VariableObservation struct {
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Expires *string `json:"expires,omitempty" tf:"expires,omitempty"`

	// A boolean flag describing if the variable value is sensitive. Defaults to false.
	IsSecret *bool `json:"isSecret,omitempty" tf:"is_secret,omitempty"`

	// The key value used for the variable. Must be unique within the Variable Group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the variable. If omitted, it will default to empty string.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type VariableParameters struct {

	// A boolean flag describing if the variable value is sensitive. Defaults to false.
	// +kubebuilder:validation:Optional
	IsSecret *bool `json:"isSecret,omitempty" tf:"is_secret,omitempty"`

	// The key value used for the variable. Must be unique within the Variable Group.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// The secret value of the variable. If omitted, it will default to empty string. Used when is_secret set to true.
	// +kubebuilder:validation:Optional
	SecretValueSecretRef *v1.SecretKeySelector `json:"secretValueSecretRef,omitempty" tf:"-"`

	// The value of the variable. If omitted, it will default to empty string.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupParameters `json:"forProvider"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Group is the Schema for the Groups API. Manages variable groups within Azure DevOps project.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.projectId)",message="projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.variable)",message="variable is a required parameter"
	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
