apiVersion: v1
kind: Secret
metadata:
  name: example-kubeconfig
  namespace: crossplane-system
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
      - cluster:
          insecure-skip-tls-verify: true                              
          server: https://todo/123
        name: target
    contexts:
      - context:
          cluster: target
          namespace: todo
          user: tfs
        name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
      - name: tfs
        user:
          token: todo
