apiVersion: azuredevops.upbound.io/v1alpha1
kind: VariableGroup
metadata:
    # crossplane.io/external-name: "9"
  name: example
spec:
  deletionPolicy: Orphan
  forProvider:
    allowAccess: true
    description: Example Variable Group Description
    name: Example Variable Group
    projectIdRef:
      name: example
    variable:
    - name: key1
      value: val1
    - isSecret: true
      name: key2
      secretValueSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system