apiVersion: v1
kind: Secret
metadata:
  name: cluster-config
  namespace: crossplane-system
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
      - cluster:
          insecure-skip-tls-verify: true                              
          server: https://kubernetes.default.svc.cluster.local
        name: target
    contexts:
      - context:
          cluster: target
          namespace: cluster-mock
          user: admin
        name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
      - name: admin
        user:
          token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkxiNE1iY0NxakhRazVSRm9xN0JrdmRBYVQ2WkdRZXZpYkJDMUpLYk1Kd3MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjbHVzdGVyLW1vY2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYWRtaW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYWRtaW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmMGU4Y2MyMS0yYTI3LTQxMDYtODE0MC05NmE2MWFiNzMyNDQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Y2x1c3Rlci1tb2NrOmFkbWluIn0.nWDExJsAQsHSexe2ZXTq4jWcq_MCaj3PSMm3IhN_HhEQexdUvDSXVdJ4Bsu8mCHX7mYg2VchWA2jvHsUbFPsGAeo6YY1uUEopfvaaY4JWRAkD6ymderWtT3IgSVl6o3V5bd9f4rdNBvtDx2aiz6CTlvnWLPjsSyiRww1amMquap_SAWRVKWVMdj5ny99N3TIx0DFbX8lTg38NH0RfyTA4tAVrfSMCbW2yP__M9PiDi5hwfsM_lDFbWVQKQFv83ia1cxjAvZcGZ0l1PWPVTwuXmJOloQOLmzO2pHrDEgbZoAy3wU1hCoREXDXBPBvVQuMSzYXfaNWIuASP6HutiWgqA

